---
title: "Linear_Model_Codes"
author: "Robert Dellinger"
date: "10/1/2022"
output: html_document
---

## Introduction

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(tidyverse)
require(modelr)
require(kableExtra)
require(plotly)

```

```{r}
iris=iris
```


```{r}
#first plot the variables to see how they are related.
scatterplot = ggplot(data = iris, aes(x = Sepal.Length ,
                        y = Sepal.Width, 
                        col = Species))+
  geom_point()+
  cowplot::theme_cowplot()+
  scale_x_continuous(breaks = seq(0,7,1.5))+
  labs(x = "Sepal length (cm)",
       y = "Sepal width (cm)")


  plotly::ggplotly(scatterplot) #%>%style()%>%layout(legend = list(x = 0.8, y = 0.95))
  
```
```{r}


scatterplot.2 = ggplot(data = iris, aes(x = Petal.Length ,
                        y = Petal.Width, 
                        col = Species))+
  geom_point(size = 2)+
  cowplot::theme_cowplot()+
  scale_x_continuous(breaks = seq(0,7,1.5))+
  labs(x = "Petal length (cm)",
       y = "Petal width (cm)")


  plotly::ggplotly(fig2) #%>%style()%>%layout(legend = list(x = 0.1, y = 0.95))
```


```{r}

#creating a linear model
petal.mod = lm(Petal.Width~Petal.Length, data = iris)
## check coefficients
coef(petal.mod)

```



```{r}
#generates evenly-spaced grid of values that covers the region where our data lies. 
grid = iris %>%
  data_grid(Petal.Length)
```

```{r}

# modelr’s function add_predictions() adds the predictions from the model to a new column 
grid  = grid%>%
  add_predictions(petal.mod)
```


```{r}

#plot predictions 
fig3 = ggplot(data = iris, aes(x = Petal.Length))+
  geom_point(aes(y = Petal.Width))+
  geom_line(data = grid, aes(y = pred), col = 2, size = 1)+
  cowplot::theme_cowplot()+
  scale_x_continuous(breaks = seq(0,7,1.5))+
  labs(x = "Petal length (cm)",
       y = "Petal width (cm)")

plotly::ggplotly(fig3)
```



```{r}
iris = iris%>%
  add_residuals(petal.mod)


iris%>%as.tibble()%>%select(5,1:4,6)%>%sample_n(12)%>%kable("html", digits = 2, align = "c", caption = "The residual values in the dataset", col.names = c("Species", "Length", "Width", "Length", "Width", "Residual"))%>%
  add_header_above(c("","Sepal" = 2, "Petal" = 2, ""))%>%
  add_header_above(c("", "Flower Measurement (cm)" = 4, ""))%>%
  column_spec(1:6, width = "8cm", color = "black", bold = FALSE)


```

```{r}
fig4 = ggplot(data = iris, aes(x = resid))+
  geom_freqpoly(binwidth = 0.5)+
  cowplot::theme_cowplot() +
  labs(x = "Model residuals",y = "Frequencies")

plotly::ggplotly(fig4)
```


```{r}
ggplot(data = iris)+
  # geom_ref_line(h = 0, colour = 2) +
  geom_point(aes(x = Petal.Length, y = resid))+
  geom_hline(yintercept = 0, linetype = 2)+
  scale_x_continuous(breaks = seq(0,7,1.5))+
  cowplot::theme_cowplot() +
  labs(x = "Petal length (cm)",
       y = "Residuals")
```



